export const PARTIAL_BOOK_SLOT_AMOUNT_RUPEES = 1500
export const PARTIAL_BOOK_SLOT_AMOUNT_PAISE = PARTIAL_BOOK_SLOT_AMOUNT_RUPEES * 100

export const FULL_BOOK_SLOT_AMOUNT_RUPEES = 3800
export const FULL_BOOK_SLOT_AMOUNT_PAISE = FULL_BOOK_SLOT_AMOUNT_RUPEES * 100

// Keeping label for places where just a simple string is needed
export const BOOK_SLOT_AMOUNT_LABEL = `₹${FULL_BOOK_SLOT_AMOUNT_RUPEES}`
